let $VIMHOME = "~/.vim"
source $VIMHOME/vundle
source $VIMHOME/vimrc_main


if has('gui_running')
  " source $HOME/.vim/bundle/vim-cobalt2/colors/cobalt2-gui.vim
  set guifont=Operator\ Mono:h13

  highlight Comment gui=italic
  highlight Comment cterm=italic

  highlight htmlArg gui=italic
  highlight htmlArg cterm=italic
endif

" Put neovim specific settings here..

" to get out of insert mode when
" results showing to scroll around
" results window
if has("nvim")
  " use interactive search & replace
  set inccommand=split
  tnoremap <Esc> <C-\><C-n>
  " so we can use escape in terminal
  tnoremap <leader>[ <Esc>
  " Windows navigation for terminal
  tnoremap <C-h> <C-\><C-n><C-w>h
  tnoremap <C-j> <C-\><C-n><C-w>j
  tnoremap <C-k> <C-\><C-n><C-w>k
  tnoremap <C-l> <C-\><C-n><C-w>l
endif

