let $VIMHOME = "~/.vim"
source $VIMHOME/vundle
source $VIMHOME/vimrc_main


if has('gui_running')
  source $HOME/.vim/bundle/vim-cobalt2/colors/cobalt2-gui.vim
  set guifont=Operator\ Mono:h12

  highlight Comment gui=italic
  highlight Comment cterm=italic

  highlight htmlArg gui=italic
  highlight htmlArg cterm=italic
endif

" Put neovim specific settings here..
if has("nvim")
  tnoremap <Esc> <C-\><C-n>
endif

